version: '3.1'

services:
  mongo:
    image: mongo:4.4.8
    container_name: "boilerplate-mongo"
    restart: always
    volumes:
      - ./.data/mongo:/data/db
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_DATABASE: boilerplate
      MONGO_INITDB_ROOT_USERNAME: boilerplate
      MONGO_INITDB_ROOT_PASSWORD: password
