/* tslint:disable */
/* eslint-disable */
/**
 * codeserk\'s web boilerplate
 * API docs for the boilerplate
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface EntryDto
 */
export interface EntryDto {
    /**
     * Entry\'s id.
     * @type {string}
     * @memberof EntryDto
     */
    id: string;
    /**
     * Id of the user that has created the entry.
     * @type {string}
     * @memberof EntryDto
     */
    userId: string;
    /**
     * Title of the entry
     * @type {string}
     * @memberof EntryDto
     */
    title: string;
    /**
     * Description of the entry.
     * @type {string}
     * @memberof EntryDto
     */
    description: string;
    /**
     * URI of the attached image
     * @type {string}
     * @memberof EntryDto
     */
    image?: string;
    /**
     * Date when the entry was added.
     * @type {string}
     * @memberof EntryDto
     */
    date: string;
}
/**
 * 
 * @export
 * @interface EntryParamsRequest
 */
export interface EntryParamsRequest {
    /**
     * Title of the entry
     * @type {string}
     * @memberof EntryParamsRequest
     */
    title: string;
    /**
     * Description of the entry.
     * @type {string}
     * @memberof EntryParamsRequest
     */
    description: string;
    /**
     * ID of the image.
     * @type {string}
     * @memberof EntryParamsRequest
     */
    image?: string;
    /**
     * Date when the entry was added.
     * @type {string}
     * @memberof EntryParamsRequest
     */
    date: string;
}
/**
 * 
 * @export
 * @interface EntryStatsQuantityResponse
 */
export interface EntryStatsQuantityResponse {
    /**
     * Stats date
     * @type {string}
     * @memberof EntryStatsQuantityResponse
     */
    date: string;
    /**
     * Quantity of entries created per day (from all the users)
     * @type {number}
     * @memberof EntryStatsQuantityResponse
     */
    quantity: number;
}
/**
 * 
 * @export
 * @interface EntryStatsResponse
 */
export interface EntryStatsResponse {
    /**
     * Quantity of entries created per day (from all the users)
     * @type {Array<EntryStatsQuantityResponse>}
     * @memberof EntryStatsResponse
     */
    entriesPerDay: Array<EntryStatsQuantityResponse>;
    /**
     * Quantity of entries created previous 7 days compared to the entries created last 7 days 
     * @type {EntryStatsWeekComparisonResponse}
     * @memberof EntryStatsResponse
     */
    entriesWeekComparison: EntryStatsWeekComparisonResponse;
}
/**
 * 
 * @export
 * @interface EntryStatsWeekComparisonResponse
 */
export interface EntryStatsWeekComparisonResponse {
    /**
     * Entries created in the previous 7 days
     * @type {number}
     * @memberof EntryStatsWeekComparisonResponse
     */
    previous7Days: number;
    /**
     * Entries created in the last 7 days
     * @type {number}
     * @memberof EntryStatsWeekComparisonResponse
     */
    last7Days: number;
}
/**
 * 
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {
    /**
     * The username
     * @type {string}
     * @memberof LoginRequest
     */
    username: string;
    /**
     * The password
     * @type {string}
     * @memberof LoginRequest
     */
    password: string;
}
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * The access token to be used for accessing the services
     * @type {string}
     * @memberof LoginResponse
     */
    token: string;
    /**
     * Authenticated user
     * @type {UserDto}
     * @memberof LoginResponse
     */
    user: UserDto;
}
/**
 * 
 * @export
 * @interface PaginatedResultResponse
 */
export interface PaginatedResultResponse {
    /**
     * Requested page
     * @type {number}
     * @memberof PaginatedResultResponse
     */
    page: number;
    /**
     * Max number of entries
     * @type {number}
     * @memberof PaginatedResultResponse
     */
    limit: number;
    /**
     * Items found in the page
     * @type {Array<PopulatedEntryDto>}
     * @memberof PaginatedResultResponse
     */
    items: Array<PopulatedEntryDto>;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PaginatedResultResponse
     */
    pages: number;
    /**
     * Total number of items
     * @type {number}
     * @memberof PaginatedResultResponse
     */
    count: number;
}
/**
 * 
 * @export
 * @interface PopulatedEntryDto
 */
export interface PopulatedEntryDto {
    /**
     * Entry\'s id.
     * @type {string}
     * @memberof PopulatedEntryDto
     */
    id: string;
    /**
     * Id of the user that has created the entry.
     * @type {string}
     * @memberof PopulatedEntryDto
     */
    userId: string;
    /**
     * Title of the entry
     * @type {string}
     * @memberof PopulatedEntryDto
     */
    title: string;
    /**
     * Description of the entry.
     * @type {string}
     * @memberof PopulatedEntryDto
     */
    description: string;
    /**
     * URI of the attached image
     * @type {string}
     * @memberof PopulatedEntryDto
     */
    image?: string;
    /**
     * Date when the entry was added.
     * @type {string}
     * @memberof PopulatedEntryDto
     */
    date: string;
    /**
     * User that added the entry
     * @type {UserDto}
     * @memberof PopulatedEntryDto
     */
    user: UserDto;
}
/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * User\'s id
     * @type {string}
     * @memberof UserDto
     */
    id: string;
    /**
     * User\'s username
     * @type {string}
     * @memberof UserDto
     */
    username: string;
    /**
     * User\'s role
     * @type {string}
     * @memberof UserDto
     */
    role: UserDtoRoleEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum UserDtoRoleEnum {
    User = 'user',
    Admin = 'admin'
}


/**
 * AdminApi - axios parameter creator
 * @export
 */
export const AdminApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Gets all entries paginated
         * @param {number} page Requested page
         * @param {number} limit Max number of items
         * @param {string} [fromDate] Initial date from which should look for entries
         * @param {string} [toDate] Final date before which should look for entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllEntriesPaginated: async (page: number, limit: number, fromDate?: string, toDate?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling getAllEntriesPaginated.');
            }
            // verify required parameter 'limit' is not null or undefined
            if (limit === null || limit === undefined) {
                throw new RequiredError('limit','Required parameter limit was null or undefined when calling getAllEntriesPaginated.');
            }
            const localVarPath = `/api/v1/admin/entries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (fromDate !== undefined) {
                localVarQueryParameter['fromDate'] = (fromDate as any instanceof Date) ?
                    (fromDate as any).toISOString() :
                    fromDate;
            }

            if (toDate !== undefined) {
                localVarQueryParameter['toDate'] = (toDate as any instanceof Date) ?
                    (toDate as any).toISOString() :
                    toDate;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets stats for the entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEntryStats: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/entries/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminApi - functional programming interface
 * @export
 */
export const AdminApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Gets all entries paginated
         * @param {number} page Requested page
         * @param {number} limit Max number of items
         * @param {string} [fromDate] Initial date from which should look for entries
         * @param {string} [toDate] Final date before which should look for entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllEntriesPaginated(page: number, limit: number, fromDate?: string, toDate?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedResultResponse>> {
            const localVarAxiosArgs = await AdminApiAxiosParamCreator(configuration).getAllEntriesPaginated(page, limit, fromDate, toDate, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Gets stats for the entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEntryStats(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntryStatsResponse>> {
            const localVarAxiosArgs = await AdminApiAxiosParamCreator(configuration).getEntryStats(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AdminApi - factory interface
 * @export
 */
export const AdminApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Gets all entries paginated
         * @param {number} page Requested page
         * @param {number} limit Max number of items
         * @param {string} [fromDate] Initial date from which should look for entries
         * @param {string} [toDate] Final date before which should look for entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllEntriesPaginated(page: number, limit: number, fromDate?: string, toDate?: string, options?: any): AxiosPromise<PaginatedResultResponse> {
            return AdminApiFp(configuration).getAllEntriesPaginated(page, limit, fromDate, toDate, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets stats for the entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEntryStats(options?: any): AxiosPromise<EntryStatsResponse> {
            return AdminApiFp(configuration).getEntryStats(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAllEntriesPaginated operation in AdminApi.
 * @export
 * @interface AdminApiGetAllEntriesPaginatedRequest
 */
export interface AdminApiGetAllEntriesPaginatedRequest {
    /**
     * Requested page
     * @type {number}
     * @memberof AdminApiGetAllEntriesPaginated
     */
    readonly page: number

    /**
     * Max number of items
     * @type {number}
     * @memberof AdminApiGetAllEntriesPaginated
     */
    readonly limit: number

    /**
     * Initial date from which should look for entries
     * @type {string}
     * @memberof AdminApiGetAllEntriesPaginated
     */
    readonly fromDate?: string

    /**
     * Final date before which should look for entries
     * @type {string}
     * @memberof AdminApiGetAllEntriesPaginated
     */
    readonly toDate?: string
}

/**
 * AdminApi - object-oriented interface
 * @export
 * @class AdminApi
 * @extends {BaseAPI}
 */
export class AdminApi extends BaseAPI {
    /**
     * Gets all entries paginated
     * @param {AdminApiGetAllEntriesPaginatedRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public getAllEntriesPaginated(requestParameters: AdminApiGetAllEntriesPaginatedRequest, options?: any) {
        return AdminApiFp(this.configuration).getAllEntriesPaginated(requestParameters.page, requestParameters.limit, requestParameters.fromDate, requestParameters.toDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets stats for the entries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public getEntryStats(options?: any) {
        return AdminApiFp(this.configuration).getEntryStats(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets the current user from thw JWT token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Log in the system using the user credentials
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest: LoginRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            if (loginRequest === null || loginRequest === undefined) {
                throw new RequiredError('loginRequest','Required parameter loginRequest was null or undefined when calling login.');
            }
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof loginRequest !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(loginRequest !== undefined ? loginRequest : {})
                : (loginRequest || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets the current user from thw JWT token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentUser(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDto>> {
            const localVarAxiosArgs = await AuthApiAxiosParamCreator(configuration).getCurrentUser(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Log in the system using the user credentials
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest: LoginRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await AuthApiAxiosParamCreator(configuration).login(loginRequest, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Gets the current user from thw JWT token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser(options?: any): AxiosPromise<UserDto> {
            return AuthApiFp(configuration).getCurrentUser(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Log in the system using the user credentials
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginRequest: LoginRequest, options?: any): AxiosPromise<LoginResponse> {
            return AuthApiFp(configuration).login(loginRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for login operation in AuthApi.
 * @export
 * @interface AuthApiLoginRequest
 */
export interface AuthApiLoginRequest {
    /**
     * 
     * @type {LoginRequest}
     * @memberof AuthApiLogin
     */
    readonly loginRequest: LoginRequest
}

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary Gets the current user from thw JWT token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public getCurrentUser(options?: any) {
        return AuthApiFp(this.configuration).getCurrentUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Log in the system using the user credentials
     * @param {AuthApiLoginRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public login(requestParameters: AuthApiLoginRequest, options?: any) {
        return AuthApiFp(this.configuration).login(requestParameters.loginRequest, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * EntriesApi - axios parameter creator
 * @export
 */
export const EntriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new diary entry
         * @param {EntryParamsRequest} entryParamsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createEntry: async (entryParamsRequest: EntryParamsRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'entryParamsRequest' is not null or undefined
            if (entryParamsRequest === null || entryParamsRequest === undefined) {
                throw new RequiredError('entryParamsRequest','Required parameter entryParamsRequest was null or undefined when calling createEntry.');
            }
            const localVarPath = `/api/v1/entries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof entryParamsRequest !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(entryParamsRequest !== undefined ? entryParamsRequest : {})
                : (entryParamsRequest || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes one entry by its id
         * @param {string} id Id of the entry
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteEntry: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling deleteEntry.');
            }
            const localVarPath = `/api/v1/entries/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets all entries paginated
         * @param {number} page Requested page
         * @param {number} limit Max number of items
         * @param {string} [fromDate] Initial date from which should look for entries
         * @param {string} [toDate] Final date before which should look for entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllEntriesPaginated: async (page: number, limit: number, fromDate?: string, toDate?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling getAllEntriesPaginated.');
            }
            // verify required parameter 'limit' is not null or undefined
            if (limit === null || limit === undefined) {
                throw new RequiredError('limit','Required parameter limit was null or undefined when calling getAllEntriesPaginated.');
            }
            const localVarPath = `/api/v1/admin/entries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (fromDate !== undefined) {
                localVarQueryParameter['fromDate'] = (fromDate as any instanceof Date) ?
                    (fromDate as any).toISOString() :
                    fromDate;
            }

            if (toDate !== undefined) {
                localVarQueryParameter['toDate'] = (toDate as any instanceof Date) ?
                    (toDate as any).toISOString() :
                    toDate;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets all the entries for the connected user
         * @param {string} [fromDate] Initial date from which should look for entries
         * @param {string} [toDate] Final date before which should look for entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEntries: async (fromDate?: string, toDate?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/entries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (fromDate !== undefined) {
                localVarQueryParameter['fromDate'] = (fromDate as any instanceof Date) ?
                    (fromDate as any).toISOString() :
                    fromDate;
            }

            if (toDate !== undefined) {
                localVarQueryParameter['toDate'] = (toDate as any instanceof Date) ?
                    (toDate as any).toISOString() :
                    toDate;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets one entry by id
         * @param {string} id Id of the entry
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEntry: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getEntry.');
            }
            const localVarPath = `/api/v1/entries/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets stats for the entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEntryStats: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/entries/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates one entry by its id
         * @param {string} id Id of the entry
         * @param {EntryParamsRequest} entryParamsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEntry: async (id: string, entryParamsRequest: EntryParamsRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling updateEntry.');
            }
            // verify required parameter 'entryParamsRequest' is not null or undefined
            if (entryParamsRequest === null || entryParamsRequest === undefined) {
                throw new RequiredError('entryParamsRequest','Required parameter entryParamsRequest was null or undefined when calling updateEntry.');
            }
            const localVarPath = `/api/v1/entries/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof entryParamsRequest !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(entryParamsRequest !== undefined ? entryParamsRequest : {})
                : (entryParamsRequest || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EntriesApi - functional programming interface
 * @export
 */
export const EntriesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Creates a new diary entry
         * @param {EntryParamsRequest} entryParamsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createEntry(entryParamsRequest: EntryParamsRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntryDto>> {
            const localVarAxiosArgs = await EntriesApiAxiosParamCreator(configuration).createEntry(entryParamsRequest, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Deletes one entry by its id
         * @param {string} id Id of the entry
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteEntry(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await EntriesApiAxiosParamCreator(configuration).deleteEntry(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Gets all entries paginated
         * @param {number} page Requested page
         * @param {number} limit Max number of items
         * @param {string} [fromDate] Initial date from which should look for entries
         * @param {string} [toDate] Final date before which should look for entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllEntriesPaginated(page: number, limit: number, fromDate?: string, toDate?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedResultResponse>> {
            const localVarAxiosArgs = await EntriesApiAxiosParamCreator(configuration).getAllEntriesPaginated(page, limit, fromDate, toDate, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Gets all the entries for the connected user
         * @param {string} [fromDate] Initial date from which should look for entries
         * @param {string} [toDate] Final date before which should look for entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEntries(fromDate?: string, toDate?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EntryDto>>> {
            const localVarAxiosArgs = await EntriesApiAxiosParamCreator(configuration).getEntries(fromDate, toDate, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Gets one entry by id
         * @param {string} id Id of the entry
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEntry(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntryDto>> {
            const localVarAxiosArgs = await EntriesApiAxiosParamCreator(configuration).getEntry(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Gets stats for the entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEntryStats(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntryStatsResponse>> {
            const localVarAxiosArgs = await EntriesApiAxiosParamCreator(configuration).getEntryStats(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Updates one entry by its id
         * @param {string} id Id of the entry
         * @param {EntryParamsRequest} entryParamsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateEntry(id: string, entryParamsRequest: EntryParamsRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntryDto>> {
            const localVarAxiosArgs = await EntriesApiAxiosParamCreator(configuration).updateEntry(id, entryParamsRequest, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * EntriesApi - factory interface
 * @export
 */
export const EntriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Creates a new diary entry
         * @param {EntryParamsRequest} entryParamsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createEntry(entryParamsRequest: EntryParamsRequest, options?: any): AxiosPromise<EntryDto> {
            return EntriesApiFp(configuration).createEntry(entryParamsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes one entry by its id
         * @param {string} id Id of the entry
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteEntry(id: string, options?: any): AxiosPromise<void> {
            return EntriesApiFp(configuration).deleteEntry(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets all entries paginated
         * @param {number} page Requested page
         * @param {number} limit Max number of items
         * @param {string} [fromDate] Initial date from which should look for entries
         * @param {string} [toDate] Final date before which should look for entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllEntriesPaginated(page: number, limit: number, fromDate?: string, toDate?: string, options?: any): AxiosPromise<PaginatedResultResponse> {
            return EntriesApiFp(configuration).getAllEntriesPaginated(page, limit, fromDate, toDate, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets all the entries for the connected user
         * @param {string} [fromDate] Initial date from which should look for entries
         * @param {string} [toDate] Final date before which should look for entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEntries(fromDate?: string, toDate?: string, options?: any): AxiosPromise<Array<EntryDto>> {
            return EntriesApiFp(configuration).getEntries(fromDate, toDate, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets one entry by id
         * @param {string} id Id of the entry
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEntry(id: string, options?: any): AxiosPromise<EntryDto> {
            return EntriesApiFp(configuration).getEntry(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets stats for the entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEntryStats(options?: any): AxiosPromise<EntryStatsResponse> {
            return EntriesApiFp(configuration).getEntryStats(options).then((request) => request(axios, basePath));
        },
        /**
         * Updates one entry by its id
         * @param {string} id Id of the entry
         * @param {EntryParamsRequest} entryParamsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEntry(id: string, entryParamsRequest: EntryParamsRequest, options?: any): AxiosPromise<EntryDto> {
            return EntriesApiFp(configuration).updateEntry(id, entryParamsRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createEntry operation in EntriesApi.
 * @export
 * @interface EntriesApiCreateEntryRequest
 */
export interface EntriesApiCreateEntryRequest {
    /**
     * 
     * @type {EntryParamsRequest}
     * @memberof EntriesApiCreateEntry
     */
    readonly entryParamsRequest: EntryParamsRequest
}

/**
 * Request parameters for deleteEntry operation in EntriesApi.
 * @export
 * @interface EntriesApiDeleteEntryRequest
 */
export interface EntriesApiDeleteEntryRequest {
    /**
     * Id of the entry
     * @type {string}
     * @memberof EntriesApiDeleteEntry
     */
    readonly id: string
}

/**
 * Request parameters for getAllEntriesPaginated operation in EntriesApi.
 * @export
 * @interface EntriesApiGetAllEntriesPaginatedRequest
 */
export interface EntriesApiGetAllEntriesPaginatedRequest {
    /**
     * Requested page
     * @type {number}
     * @memberof EntriesApiGetAllEntriesPaginated
     */
    readonly page: number

    /**
     * Max number of items
     * @type {number}
     * @memberof EntriesApiGetAllEntriesPaginated
     */
    readonly limit: number

    /**
     * Initial date from which should look for entries
     * @type {string}
     * @memberof EntriesApiGetAllEntriesPaginated
     */
    readonly fromDate?: string

    /**
     * Final date before which should look for entries
     * @type {string}
     * @memberof EntriesApiGetAllEntriesPaginated
     */
    readonly toDate?: string
}

/**
 * Request parameters for getEntries operation in EntriesApi.
 * @export
 * @interface EntriesApiGetEntriesRequest
 */
export interface EntriesApiGetEntriesRequest {
    /**
     * Initial date from which should look for entries
     * @type {string}
     * @memberof EntriesApiGetEntries
     */
    readonly fromDate?: string

    /**
     * Final date before which should look for entries
     * @type {string}
     * @memberof EntriesApiGetEntries
     */
    readonly toDate?: string
}

/**
 * Request parameters for getEntry operation in EntriesApi.
 * @export
 * @interface EntriesApiGetEntryRequest
 */
export interface EntriesApiGetEntryRequest {
    /**
     * Id of the entry
     * @type {string}
     * @memberof EntriesApiGetEntry
     */
    readonly id: string
}

/**
 * Request parameters for updateEntry operation in EntriesApi.
 * @export
 * @interface EntriesApiUpdateEntryRequest
 */
export interface EntriesApiUpdateEntryRequest {
    /**
     * Id of the entry
     * @type {string}
     * @memberof EntriesApiUpdateEntry
     */
    readonly id: string

    /**
     * 
     * @type {EntryParamsRequest}
     * @memberof EntriesApiUpdateEntry
     */
    readonly entryParamsRequest: EntryParamsRequest
}

/**
 * EntriesApi - object-oriented interface
 * @export
 * @class EntriesApi
 * @extends {BaseAPI}
 */
export class EntriesApi extends BaseAPI {
    /**
     * Creates a new diary entry
     * @param {EntriesApiCreateEntryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApi
     */
    public createEntry(requestParameters: EntriesApiCreateEntryRequest, options?: any) {
        return EntriesApiFp(this.configuration).createEntry(requestParameters.entryParamsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes one entry by its id
     * @param {EntriesApiDeleteEntryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApi
     */
    public deleteEntry(requestParameters: EntriesApiDeleteEntryRequest, options?: any) {
        return EntriesApiFp(this.configuration).deleteEntry(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets all entries paginated
     * @param {EntriesApiGetAllEntriesPaginatedRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApi
     */
    public getAllEntriesPaginated(requestParameters: EntriesApiGetAllEntriesPaginatedRequest, options?: any) {
        return EntriesApiFp(this.configuration).getAllEntriesPaginated(requestParameters.page, requestParameters.limit, requestParameters.fromDate, requestParameters.toDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets all the entries for the connected user
     * @param {EntriesApiGetEntriesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApi
     */
    public getEntries(requestParameters: EntriesApiGetEntriesRequest = {}, options?: any) {
        return EntriesApiFp(this.configuration).getEntries(requestParameters.fromDate, requestParameters.toDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets one entry by id
     * @param {EntriesApiGetEntryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApi
     */
    public getEntry(requestParameters: EntriesApiGetEntryRequest, options?: any) {
        return EntriesApiFp(this.configuration).getEntry(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets stats for the entries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApi
     */
    public getEntryStats(options?: any) {
        return EntriesApiFp(this.configuration).getEntryStats(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates one entry by its id
     * @param {EntriesApiUpdateEntryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApi
     */
    public updateEntry(requestParameters: EntriesApiUpdateEntryRequest, options?: any) {
        return EntriesApiFp(this.configuration).updateEntry(requestParameters.id, requestParameters.entryParamsRequest, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * MediaApi - axios parameter creator
 * @export
 */
export const MediaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mediaControllerGetFile: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling mediaControllerGetFile.');
            }
            const localVarPath = `/api/v1/media/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {any} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mediaControllerUploadFile: async (file?: any, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/media`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MediaApi - functional programming interface
 * @export
 */
export const MediaApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaControllerGetFile(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await MediaApiAxiosParamCreator(configuration).mediaControllerGetFile(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {any} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaControllerUploadFile(file?: any, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await MediaApiAxiosParamCreator(configuration).mediaControllerUploadFile(file, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MediaApi - factory interface
 * @export
 */
export const MediaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mediaControllerGetFile(id: string, options?: any): AxiosPromise<void> {
            return MediaApiFp(configuration).mediaControllerGetFile(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {any} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mediaControllerUploadFile(file?: any, options?: any): AxiosPromise<string> {
            return MediaApiFp(configuration).mediaControllerUploadFile(file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for mediaControllerGetFile operation in MediaApi.
 * @export
 * @interface MediaApiMediaControllerGetFileRequest
 */
export interface MediaApiMediaControllerGetFileRequest {
    /**
     * 
     * @type {string}
     * @memberof MediaApiMediaControllerGetFile
     */
    readonly id: string
}

/**
 * Request parameters for mediaControllerUploadFile operation in MediaApi.
 * @export
 * @interface MediaApiMediaControllerUploadFileRequest
 */
export interface MediaApiMediaControllerUploadFileRequest {
    /**
     * 
     * @type {any}
     * @memberof MediaApiMediaControllerUploadFile
     */
    readonly file?: any
}

/**
 * MediaApi - object-oriented interface
 * @export
 * @class MediaApi
 * @extends {BaseAPI}
 */
export class MediaApi extends BaseAPI {
    /**
     * 
     * @param {MediaApiMediaControllerGetFileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApi
     */
    public mediaControllerGetFile(requestParameters: MediaApiMediaControllerGetFileRequest, options?: any) {
        return MediaApiFp(this.configuration).mediaControllerGetFile(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {MediaApiMediaControllerUploadFileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApi
     */
    public mediaControllerUploadFile(requestParameters: MediaApiMediaControllerUploadFileRequest = {}, options?: any) {
        return MediaApiFp(this.configuration).mediaControllerUploadFile(requestParameters.file, options).then((request) => request(this.axios, this.basePath));
    }
}


